// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:producer.Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bytes body = 2;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
