// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

public interface ResolveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:producer.ResolveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>repeated .producer.Payload payloads = 2;</code>
   */
  java.util.List<o3.souse.producer.Payload> 
      getPayloadsList();
  /**
   * <code>repeated .producer.Payload payloads = 2;</code>
   */
  o3.souse.producer.Payload getPayloads(int index);
  /**
   * <code>repeated .producer.Payload payloads = 2;</code>
   */
  int getPayloadsCount();
  /**
   * <code>repeated .producer.Payload payloads = 2;</code>
   */
  java.util.List<? extends o3.souse.producer.PayloadOrBuilder> 
      getPayloadsOrBuilderList();
  /**
   * <code>repeated .producer.Payload payloads = 2;</code>
   */
  o3.souse.producer.PayloadOrBuilder getPayloadsOrBuilder(
      int index);
}
