// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

public interface ResolveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:producer.ResolveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>repeated string names = 2;</code>
   * @return A list containing the names.
   */
  java.util.List<java.lang.String>
      getNamesList();
  /**
   * <code>repeated string names = 2;</code>
   * @return The count of names.
   */
  int getNamesCount();
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the element to return.
   * @return The names at the given index.
   */
  java.lang.String getNames(int index);
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the names at the given index.
   */
  com.google.protobuf.ByteString
      getNamesBytes(int index);

  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  java.util.List<o3.souse.producer.Payload> 
      getPayloadsList();
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  o3.souse.producer.Payload getPayloads(int index);
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  int getPayloadsCount();
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  java.util.List<? extends o3.souse.producer.PayloadOrBuilder> 
      getPayloadsOrBuilderList();
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  o3.souse.producer.PayloadOrBuilder getPayloadsOrBuilder(
      int index);
}
