// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

/**
 * Protobuf type {@code producer.ResolveMessage}
 */
public final class ResolveMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:producer.ResolveMessage)
    ResolveMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResolveMessage.newBuilder() to construct.
  private ResolveMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResolveMessage() {
    requestId_ = "";
    names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    payloads_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResolveMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResolveMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              names_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            names_.add(s);
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              payloads_ = new java.util.ArrayList<o3.souse.producer.Payload>();
              mutable_bitField0_ |= 0x00000002;
            }
            payloads_.add(
                input.readMessage(o3.souse.producer.Payload.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        names_ = names_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        payloads_ = java.util.Collections.unmodifiableList(payloads_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            o3.souse.producer.ResolveMessage.class, o3.souse.producer.ResolveMessage.Builder.class);
  }

  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList names_;
  /**
   * <code>repeated string names = 2;</code>
   * @return A list containing the names.
   */
  public com.google.protobuf.ProtocolStringList
      getNamesList() {
    return names_;
  }
  /**
   * <code>repeated string names = 2;</code>
   * @return The count of names.
   */
  public int getNamesCount() {
    return names_.size();
  }
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the element to return.
   * @return The names at the given index.
   */
  public java.lang.String getNames(int index) {
    return names_.get(index);
  }
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the names at the given index.
   */
  public com.google.protobuf.ByteString
      getNamesBytes(int index) {
    return names_.getByteString(index);
  }

  public static final int PAYLOADS_FIELD_NUMBER = 3;
  private java.util.List<o3.souse.producer.Payload> payloads_;
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  @java.lang.Override
  public java.util.List<o3.souse.producer.Payload> getPayloadsList() {
    return payloads_;
  }
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends o3.souse.producer.PayloadOrBuilder> 
      getPayloadsOrBuilderList() {
    return payloads_;
  }
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  @java.lang.Override
  public int getPayloadsCount() {
    return payloads_.size();
  }
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  @java.lang.Override
  public o3.souse.producer.Payload getPayloads(int index) {
    return payloads_.get(index);
  }
  /**
   * <code>repeated .producer.Payload payloads = 3;</code>
   */
  @java.lang.Override
  public o3.souse.producer.PayloadOrBuilder getPayloadsOrBuilder(
      int index) {
    return payloads_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    for (int i = 0; i < names_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, names_.getRaw(i));
    }
    for (int i = 0; i < payloads_.size(); i++) {
      output.writeMessage(3, payloads_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < names_.size(); i++) {
        dataSize += computeStringSizeNoTag(names_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNamesList().size();
    }
    for (int i = 0; i < payloads_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, payloads_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof o3.souse.producer.ResolveMessage)) {
      return super.equals(obj);
    }
    o3.souse.producer.ResolveMessage other = (o3.souse.producer.ResolveMessage) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getNamesList()
        .equals(other.getNamesList())) return false;
    if (!getPayloadsList()
        .equals(other.getPayloadsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    if (getNamesCount() > 0) {
      hash = (37 * hash) + NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getNamesList().hashCode();
    }
    if (getPayloadsCount() > 0) {
      hash = (37 * hash) + PAYLOADS_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static o3.souse.producer.ResolveMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static o3.souse.producer.ResolveMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(o3.souse.producer.ResolveMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code producer.ResolveMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:producer.ResolveMessage)
      o3.souse.producer.ResolveMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              o3.souse.producer.ResolveMessage.class, o3.souse.producer.ResolveMessage.Builder.class);
    }

    // Construct using o3.souse.producer.ResolveMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPayloadsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = "";

      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (payloadsBuilder_ == null) {
        payloads_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        payloadsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_descriptor;
    }

    @java.lang.Override
    public o3.souse.producer.ResolveMessage getDefaultInstanceForType() {
      return o3.souse.producer.ResolveMessage.getDefaultInstance();
    }

    @java.lang.Override
    public o3.souse.producer.ResolveMessage build() {
      o3.souse.producer.ResolveMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public o3.souse.producer.ResolveMessage buildPartial() {
      o3.souse.producer.ResolveMessage result = new o3.souse.producer.ResolveMessage(this);
      int from_bitField0_ = bitField0_;
      result.requestId_ = requestId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        names_ = names_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.names_ = names_;
      if (payloadsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          payloads_ = java.util.Collections.unmodifiableList(payloads_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.payloads_ = payloads_;
      } else {
        result.payloads_ = payloadsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof o3.souse.producer.ResolveMessage) {
        return mergeFrom((o3.souse.producer.ResolveMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(o3.souse.producer.ResolveMessage other) {
      if (other == o3.souse.producer.ResolveMessage.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (!other.names_.isEmpty()) {
        if (names_.isEmpty()) {
          names_ = other.names_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNamesIsMutable();
          names_.addAll(other.names_);
        }
        onChanged();
      }
      if (payloadsBuilder_ == null) {
        if (!other.payloads_.isEmpty()) {
          if (payloads_.isEmpty()) {
            payloads_ = other.payloads_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePayloadsIsMutable();
            payloads_.addAll(other.payloads_);
          }
          onChanged();
        }
      } else {
        if (!other.payloads_.isEmpty()) {
          if (payloadsBuilder_.isEmpty()) {
            payloadsBuilder_.dispose();
            payloadsBuilder_ = null;
            payloads_ = other.payloads_;
            bitField0_ = (bitField0_ & ~0x00000002);
            payloadsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPayloadsFieldBuilder() : null;
          } else {
            payloadsBuilder_.addAllMessages(other.payloads_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      o3.souse.producer.ResolveMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (o3.souse.producer.ResolveMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object requestId_ = "";
    /**
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        names_ = new com.google.protobuf.LazyStringArrayList(names_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string names = 2;</code>
     * @return A list containing the names.
     */
    public com.google.protobuf.ProtocolStringList
        getNamesList() {
      return names_.getUnmodifiableView();
    }
    /**
     * <code>repeated string names = 2;</code>
     * @return The count of names.
     */
    public int getNamesCount() {
      return names_.size();
    }
    /**
     * <code>repeated string names = 2;</code>
     * @param index The index of the element to return.
     * @return The names at the given index.
     */
    public java.lang.String getNames(int index) {
      return names_.get(index);
    }
    /**
     * <code>repeated string names = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the names at the given index.
     */
    public com.google.protobuf.ByteString
        getNamesBytes(int index) {
      return names_.getByteString(index);
    }
    /**
     * <code>repeated string names = 2;</code>
     * @param index The index to set the value at.
     * @param value The names to set.
     * @return This builder for chaining.
     */
    public Builder setNames(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
      names_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string names = 2;</code>
     * @param value The names to add.
     * @return This builder for chaining.
     */
    public Builder addNames(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
      names_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string names = 2;</code>
     * @param values The names to add.
     * @return This builder for chaining.
     */
    public Builder addAllNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, names_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string names = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNames() {
      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string names = 2;</code>
     * @param value The bytes of the names to add.
     * @return This builder for chaining.
     */
    public Builder addNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureNamesIsMutable();
      names_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<o3.souse.producer.Payload> payloads_ =
      java.util.Collections.emptyList();
    private void ensurePayloadsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        payloads_ = new java.util.ArrayList<o3.souse.producer.Payload>(payloads_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        o3.souse.producer.Payload, o3.souse.producer.Payload.Builder, o3.souse.producer.PayloadOrBuilder> payloadsBuilder_;

    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public java.util.List<o3.souse.producer.Payload> getPayloadsList() {
      if (payloadsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(payloads_);
      } else {
        return payloadsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public int getPayloadsCount() {
      if (payloadsBuilder_ == null) {
        return payloads_.size();
      } else {
        return payloadsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public o3.souse.producer.Payload getPayloads(int index) {
      if (payloadsBuilder_ == null) {
        return payloads_.get(index);
      } else {
        return payloadsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder setPayloads(
        int index, o3.souse.producer.Payload value) {
      if (payloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadsIsMutable();
        payloads_.set(index, value);
        onChanged();
      } else {
        payloadsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder setPayloads(
        int index, o3.souse.producer.Payload.Builder builderForValue) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.set(index, builderForValue.build());
        onChanged();
      } else {
        payloadsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder addPayloads(o3.souse.producer.Payload value) {
      if (payloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadsIsMutable();
        payloads_.add(value);
        onChanged();
      } else {
        payloadsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder addPayloads(
        int index, o3.souse.producer.Payload value) {
      if (payloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadsIsMutable();
        payloads_.add(index, value);
        onChanged();
      } else {
        payloadsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder addPayloads(
        o3.souse.producer.Payload.Builder builderForValue) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.add(builderForValue.build());
        onChanged();
      } else {
        payloadsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder addPayloads(
        int index, o3.souse.producer.Payload.Builder builderForValue) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.add(index, builderForValue.build());
        onChanged();
      } else {
        payloadsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder addAllPayloads(
        java.lang.Iterable<? extends o3.souse.producer.Payload> values) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payloads_);
        onChanged();
      } else {
        payloadsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder clearPayloads() {
      if (payloadsBuilder_ == null) {
        payloads_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        payloadsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public Builder removePayloads(int index) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.remove(index);
        onChanged();
      } else {
        payloadsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public o3.souse.producer.Payload.Builder getPayloadsBuilder(
        int index) {
      return getPayloadsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public o3.souse.producer.PayloadOrBuilder getPayloadsOrBuilder(
        int index) {
      if (payloadsBuilder_ == null) {
        return payloads_.get(index);  } else {
        return payloadsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public java.util.List<? extends o3.souse.producer.PayloadOrBuilder> 
         getPayloadsOrBuilderList() {
      if (payloadsBuilder_ != null) {
        return payloadsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(payloads_);
      }
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public o3.souse.producer.Payload.Builder addPayloadsBuilder() {
      return getPayloadsFieldBuilder().addBuilder(
          o3.souse.producer.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public o3.souse.producer.Payload.Builder addPayloadsBuilder(
        int index) {
      return getPayloadsFieldBuilder().addBuilder(
          index, o3.souse.producer.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .producer.Payload payloads = 3;</code>
     */
    public java.util.List<o3.souse.producer.Payload.Builder> 
         getPayloadsBuilderList() {
      return getPayloadsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        o3.souse.producer.Payload, o3.souse.producer.Payload.Builder, o3.souse.producer.PayloadOrBuilder> 
        getPayloadsFieldBuilder() {
      if (payloadsBuilder_ == null) {
        payloadsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            o3.souse.producer.Payload, o3.souse.producer.Payload.Builder, o3.souse.producer.PayloadOrBuilder>(
                payloads_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        payloads_ = null;
      }
      return payloadsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:producer.ResolveMessage)
  }

  // @@protoc_insertion_point(class_scope:producer.ResolveMessage)
  private static final o3.souse.producer.ResolveMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new o3.souse.producer.ResolveMessage();
  }

  public static o3.souse.producer.ResolveMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResolveMessage>
      PARSER = new com.google.protobuf.AbstractParser<ResolveMessage>() {
    @java.lang.Override
    public ResolveMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResolveMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResolveMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResolveMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public o3.souse.producer.ResolveMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

