// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

/**
 * Protobuf type {@code producer.ResolveMessage}
 */
public final class ResolveMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:producer.ResolveMessage)
    ResolveMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResolveMessage.newBuilder() to construct.
  private ResolveMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResolveMessage() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResolveMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResolveMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            payloadCase_ = 2;
            payload_ = input.readBytes();
            break;
          }
          case 24: {
            payloadCase_ = 3;
            payload_ = input.readInt32();
            break;
          }
          case 37: {
            payloadCase_ = 4;
            payload_ = input.readFloat();
            break;
          }
          case 40: {
            payloadCase_ = 5;
            payload_ = input.readBool();
            break;
          }
          case 48: {
            payloadCase_ = 6;
            payload_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            o3.souse.producer.ResolveMessage.class, o3.souse.producer.ResolveMessage.Builder.class);
  }

  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    BLOBVALUE(2),
    INTVALUE(3),
    FPVALUE(4),
    BOOLVALUE(5),
    REQUESTED(6),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return BLOBVALUE;
        case 3: return INTVALUE;
        case 4: return FPVALUE;
        case 5: return BOOLVALUE;
        case 6: return REQUESTED;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOBVALUE_FIELD_NUMBER = 2;
  /**
   * <code>bytes blobValue = 2;</code>
   * @return Whether the blobValue field is set.
   */
  @java.lang.Override
  public boolean hasBlobValue() {
    return payloadCase_ == 2;
  }
  /**
   * <code>bytes blobValue = 2;</code>
   * @return The blobValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBlobValue() {
    if (payloadCase_ == 2) {
      return (com.google.protobuf.ByteString) payload_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int INTVALUE_FIELD_NUMBER = 3;
  /**
   * <code>int32 intValue = 3;</code>
   * @return Whether the intValue field is set.
   */
  @java.lang.Override
  public boolean hasIntValue() {
    return payloadCase_ == 3;
  }
  /**
   * <code>int32 intValue = 3;</code>
   * @return The intValue.
   */
  @java.lang.Override
  public int getIntValue() {
    if (payloadCase_ == 3) {
      return (java.lang.Integer) payload_;
    }
    return 0;
  }

  public static final int FPVALUE_FIELD_NUMBER = 4;
  /**
   * <code>float fpValue = 4;</code>
   * @return Whether the fpValue field is set.
   */
  @java.lang.Override
  public boolean hasFpValue() {
    return payloadCase_ == 4;
  }
  /**
   * <code>float fpValue = 4;</code>
   * @return The fpValue.
   */
  @java.lang.Override
  public float getFpValue() {
    if (payloadCase_ == 4) {
      return (java.lang.Float) payload_;
    }
    return 0F;
  }

  public static final int BOOLVALUE_FIELD_NUMBER = 5;
  /**
   * <code>bool boolValue = 5;</code>
   * @return Whether the boolValue field is set.
   */
  @java.lang.Override
  public boolean hasBoolValue() {
    return payloadCase_ == 5;
  }
  /**
   * <code>bool boolValue = 5;</code>
   * @return The boolValue.
   */
  @java.lang.Override
  public boolean getBoolValue() {
    if (payloadCase_ == 5) {
      return (java.lang.Boolean) payload_;
    }
    return false;
  }

  public static final int REQUESTED_FIELD_NUMBER = 6;
  /**
   * <code>bool requested = 6;</code>
   * @return Whether the requested field is set.
   */
  @java.lang.Override
  public boolean hasRequested() {
    return payloadCase_ == 6;
  }
  /**
   * <code>bool requested = 6;</code>
   * @return The requested.
   */
  @java.lang.Override
  public boolean getRequested() {
    if (payloadCase_ == 6) {
      return (java.lang.Boolean) payload_;
    }
    return false;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (payloadCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeInt32(
          3, (int)((java.lang.Integer) payload_));
    }
    if (payloadCase_ == 4) {
      output.writeFloat(
          4, (float)((java.lang.Float) payload_));
    }
    if (payloadCase_ == 5) {
      output.writeBool(
          5, (boolean)((java.lang.Boolean) payload_));
    }
    if (payloadCase_ == 6) {
      output.writeBool(
          6, (boolean)((java.lang.Boolean) payload_));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            3, (int)((java.lang.Integer) payload_));
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(
            4, (float)((java.lang.Float) payload_));
    }
    if (payloadCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            5, (boolean)((java.lang.Boolean) payload_));
    }
    if (payloadCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            6, (boolean)((java.lang.Boolean) payload_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof o3.souse.producer.ResolveMessage)) {
      return super.equals(obj);
    }
    o3.souse.producer.ResolveMessage other = (o3.souse.producer.ResolveMessage) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 2:
        if (!getBlobValue()
            .equals(other.getBlobValue())) return false;
        break;
      case 3:
        if (getIntValue()
            != other.getIntValue()) return false;
        break;
      case 4:
        if (java.lang.Float.floatToIntBits(getFpValue())
            != java.lang.Float.floatToIntBits(
                other.getFpValue())) return false;
        break;
      case 5:
        if (getBoolValue()
            != other.getBoolValue()) return false;
        break;
      case 6:
        if (getRequested()
            != other.getRequested()) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    switch (payloadCase_) {
      case 2:
        hash = (37 * hash) + BLOBVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getBlobValue().hashCode();
        break;
      case 3:
        hash = (37 * hash) + INTVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getIntValue();
        break;
      case 4:
        hash = (37 * hash) + FPVALUE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getFpValue());
        break;
      case 5:
        hash = (37 * hash) + BOOLVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolValue());
        break;
      case 6:
        hash = (37 * hash) + REQUESTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRequested());
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static o3.souse.producer.ResolveMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static o3.souse.producer.ResolveMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static o3.souse.producer.ResolveMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(o3.souse.producer.ResolveMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code producer.ResolveMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:producer.ResolveMessage)
      o3.souse.producer.ResolveMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              o3.souse.producer.ResolveMessage.class, o3.souse.producer.ResolveMessage.Builder.class);
    }

    // Construct using o3.souse.producer.ResolveMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return o3.souse.producer.SoUseProducerService.internal_static_producer_ResolveMessage_descriptor;
    }

    @java.lang.Override
    public o3.souse.producer.ResolveMessage getDefaultInstanceForType() {
      return o3.souse.producer.ResolveMessage.getDefaultInstance();
    }

    @java.lang.Override
    public o3.souse.producer.ResolveMessage build() {
      o3.souse.producer.ResolveMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public o3.souse.producer.ResolveMessage buildPartial() {
      o3.souse.producer.ResolveMessage result = new o3.souse.producer.ResolveMessage(this);
      result.name_ = name_;
      if (payloadCase_ == 2) {
        result.payload_ = payload_;
      }
      if (payloadCase_ == 3) {
        result.payload_ = payload_;
      }
      if (payloadCase_ == 4) {
        result.payload_ = payload_;
      }
      if (payloadCase_ == 5) {
        result.payload_ = payload_;
      }
      if (payloadCase_ == 6) {
        result.payload_ = payload_;
      }
      result.payloadCase_ = payloadCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof o3.souse.producer.ResolveMessage) {
        return mergeFrom((o3.souse.producer.ResolveMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(o3.souse.producer.ResolveMessage other) {
      if (other == o3.souse.producer.ResolveMessage.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      switch (other.getPayloadCase()) {
        case BLOBVALUE: {
          setBlobValue(other.getBlobValue());
          break;
        }
        case INTVALUE: {
          setIntValue(other.getIntValue());
          break;
        }
        case FPVALUE: {
          setFpValue(other.getFpValue());
          break;
        }
        case BOOLVALUE: {
          setBoolValue(other.getBoolValue());
          break;
        }
        case REQUESTED: {
          setRequested(other.getRequested());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      o3.souse.producer.ResolveMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (o3.souse.producer.ResolveMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bytes blobValue = 2;</code>
     * @return Whether the blobValue field is set.
     */
    public boolean hasBlobValue() {
      return payloadCase_ == 2;
    }
    /**
     * <code>bytes blobValue = 2;</code>
     * @return The blobValue.
     */
    public com.google.protobuf.ByteString getBlobValue() {
      if (payloadCase_ == 2) {
        return (com.google.protobuf.ByteString) payload_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes blobValue = 2;</code>
     * @param value The blobValue to set.
     * @return This builder for chaining.
     */
    public Builder setBlobValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  payloadCase_ = 2;
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes blobValue = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlobValue() {
      if (payloadCase_ == 2) {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>int32 intValue = 3;</code>
     * @return Whether the intValue field is set.
     */
    public boolean hasIntValue() {
      return payloadCase_ == 3;
    }
    /**
     * <code>int32 intValue = 3;</code>
     * @return The intValue.
     */
    public int getIntValue() {
      if (payloadCase_ == 3) {
        return (java.lang.Integer) payload_;
      }
      return 0;
    }
    /**
     * <code>int32 intValue = 3;</code>
     * @param value The intValue to set.
     * @return This builder for chaining.
     */
    public Builder setIntValue(int value) {
      payloadCase_ = 3;
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 intValue = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntValue() {
      if (payloadCase_ == 3) {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>float fpValue = 4;</code>
     * @return Whether the fpValue field is set.
     */
    public boolean hasFpValue() {
      return payloadCase_ == 4;
    }
    /**
     * <code>float fpValue = 4;</code>
     * @return The fpValue.
     */
    public float getFpValue() {
      if (payloadCase_ == 4) {
        return (java.lang.Float) payload_;
      }
      return 0F;
    }
    /**
     * <code>float fpValue = 4;</code>
     * @param value The fpValue to set.
     * @return This builder for chaining.
     */
    public Builder setFpValue(float value) {
      payloadCase_ = 4;
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float fpValue = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFpValue() {
      if (payloadCase_ == 4) {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool boolValue = 5;</code>
     * @return Whether the boolValue field is set.
     */
    public boolean hasBoolValue() {
      return payloadCase_ == 5;
    }
    /**
     * <code>bool boolValue = 5;</code>
     * @return The boolValue.
     */
    public boolean getBoolValue() {
      if (payloadCase_ == 5) {
        return (java.lang.Boolean) payload_;
      }
      return false;
    }
    /**
     * <code>bool boolValue = 5;</code>
     * @param value The boolValue to set.
     * @return This builder for chaining.
     */
    public Builder setBoolValue(boolean value) {
      payloadCase_ = 5;
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool boolValue = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolValue() {
      if (payloadCase_ == 5) {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>bool requested = 6;</code>
     * @return Whether the requested field is set.
     */
    public boolean hasRequested() {
      return payloadCase_ == 6;
    }
    /**
     * <code>bool requested = 6;</code>
     * @return The requested.
     */
    public boolean getRequested() {
      if (payloadCase_ == 6) {
        return (java.lang.Boolean) payload_;
      }
      return false;
    }
    /**
     * <code>bool requested = 6;</code>
     * @param value The requested to set.
     * @return This builder for chaining.
     */
    public Builder setRequested(boolean value) {
      payloadCase_ = 6;
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool requested = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequested() {
      if (payloadCase_ == 6) {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
      }
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:producer.ResolveMessage)
  }

  // @@protoc_insertion_point(class_scope:producer.ResolveMessage)
  private static final o3.souse.producer.ResolveMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new o3.souse.producer.ResolveMessage();
  }

  public static o3.souse.producer.ResolveMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResolveMessage>
      PARSER = new com.google.protobuf.AbstractParser<ResolveMessage>() {
    @java.lang.Override
    public ResolveMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResolveMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResolveMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResolveMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public o3.souse.producer.ResolveMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

