// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

public interface ResolveMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:producer.ResolveMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.producer.Payload payloads = 2;</code>
   * @return Whether the payloads field is set.
   */
  boolean hasPayloads();
  /**
   * <code>.producer.Payload payloads = 2;</code>
   * @return The payloads.
   */
  o3.souse.producer.Payload getPayloads();
  /**
   * <code>.producer.Payload payloads = 2;</code>
   */
  o3.souse.producer.PayloadOrBuilder getPayloadsOrBuilder();

  /**
   * <code>bool requested = 3;</code>
   * @return Whether the requested field is set.
   */
  boolean hasRequested();
  /**
   * <code>bool requested = 3;</code>
   * @return The requested.
   */
  boolean getRequested();

  public o3.souse.producer.ResolveMessage.ValueCase getValueCase();
}
