// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

public final class SoUseProducerService {
  private SoUseProducerService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_producer_ResolveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_producer_ResolveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_producer_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_producer_Payload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_producer_ResolveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_producer_ResolveResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016producer.proto\022\010producer\"X\n\016ResolveReq" +
      "uest\022\022\n\nrequest_id\030\001 \001(\t\022\r\n\005names\030\002 \003(\t\022" +
      "#\n\010payloads\030\003 \003(\0132\021.producer.Payload\"%\n\007" +
      "Payload\022\014\n\004name\030\001 \001(\t\022\014\n\004body\030\002 \001(\014\"J\n\017R" +
      "esolveResponse\022\022\n\nrequest_id\030\001 \001(\t\022#\n\010pa" +
      "yloads\030\002 \003(\0132\021.producer.Payload2\235\001\n\rSoUs" +
      "eProducer\022@\n\007resolve\022\030.producer.ResolveR" +
      "equest\032\031.producer.ResolveResponse\"\000\022J\n\rr" +
      "esolveStream\022\030.producer.ResolveRequest\032\031" +
      ".producer.ResolveResponse\"\000(\0010\001B+\n\021o3.so" +
      "use.producerB\024SoUseProducerServiceP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_producer_ResolveRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_producer_ResolveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_producer_ResolveRequest_descriptor,
        new java.lang.String[] { "RequestId", "Names", "Payloads", });
    internal_static_producer_Payload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_producer_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_producer_Payload_descriptor,
        new java.lang.String[] { "Name", "Body", });
    internal_static_producer_ResolveResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_producer_ResolveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_producer_ResolveResponse_descriptor,
        new java.lang.String[] { "RequestId", "Payloads", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
