// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: producer.proto

package o3.souse.producer;

public final class SoUseProducerService {
  private SoUseProducerService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_producer_ResolveMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_producer_ResolveMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016producer.proto\022\010producer\"\217\001\n\016ResolveMe" +
      "ssage\022\014\n\004name\030\001 \001(\t\022\023\n\tblobValue\030\002 \001(\014H\000" +
      "\022\022\n\010intValue\030\003 \001(\005H\000\022\021\n\007fpValue\030\004 \001(\002H\000\022" +
      "\023\n\tboolValue\030\005 \001(\010H\000\022\023\n\trequested\030\006 \001(\010H" +
      "\000B\t\n\007payload2Z\n\rSoUseProducer\022I\n\rresolve" +
      "Stream\022\030.producer.ResolveMessage\032\030.produ" +
      "cer.ResolveMessage\"\000(\0010\001B+\n\021o3.souse.pro" +
      "ducerB\024SoUseProducerServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_producer_ResolveMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_producer_ResolveMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_producer_ResolveMessage_descriptor,
        new java.lang.String[] { "Name", "BlobValue", "IntValue", "FpValue", "BoolValue", "Requested", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
